---
driver:
  name: docker
lint:
  set -e
  yamllint **/*.yml -c molecule/yamllint.yml
  ansible-lint
  flake8
platforms:
  - name: centos8
    image: geerlingguy/docker-centos8-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
scenario:
  name: default
verifier:
  name: testinfra
